# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import capturePage
import netifaces
import deviceSetup
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 280)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.save_toCapture = QtWidgets.QPushButton(self.centralwidget)
        self.save_toCapture.setGeometry(QtCore.QRect(200, 120, 400, 91))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.save_toCapture.setFont(font)
        self.save_toCapture.setObjectName("save_toCapture")
        self.save_toCapture.clicked.connect(self.set_interfaces)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 50, 503, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.comboBox_inputInterface = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_inputInterface.setObjectName("comboBox_inputInterface")
        self.comboBox_inputInterface.addItems(netifaces.interfaces())

        self.gridLayout.addWidget(self.comboBox_inputInterface, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.comboBox_outputInterface = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_outputInterface.setObjectName("comboBox_outputInterface")

        self.comboBox_outputInterface.addItems(netifaces.interfaces())

        self.gridLayout.addWidget(self.comboBox_outputInterface, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Main", "Main"))
        self.save_toCapture.setText(_translate("MainWindow", "Save and continue to capture page."))
        self.label.setText(_translate("MainWindow", "Select input interface:"))
        self.label_2.setText(_translate("MainWindow", "Select output interface:"))

    def to_capturePage(self):
        self.captureWindow = QtWidgets.QMainWindow()
        self.ui = capturePage.Ui_captureWindow()
        self.ui.setupUi(self.captureWindow, deviceSetup.input_interface)
        self.captureWindow.show()

    def set_interfaces(self):
        deviceSetup.input_interface = self.comboBox_inputInterface.currentText()
        deviceSetup.output_interface = self.comboBox_outputInterface.currentText()
        deviceSetup.configure_device()
        self.to_capturePage()

    # def to_proxyPage(self):
    #     self.proxyWindow = QtWidgets.QMainWindow()
    #     self.ui = proxyPage.Ui_ProxyWindow()
    #     self.ui.setupUi(self.proxyWindow)
    #     self.proxyWindow.show()

    def get_inputInterface(self):
        return deviceSetup.input_interface


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
